version: 2
jobs: # a collection of steps
  build:
    environment:
      # Configure the JVM and Gradle to avoid OOM errors
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
    docker: # run the steps with Docker
      - image: cimg/openjdk:11.0-node # ...with this image as the primary container; this is where all `steps` will run
    steps: # a collection of executable commands
      - checkout # check out source code to working directory
      # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
      # - restore_cache:
      #     key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      # - restore_cache:
      #     key: v1-gradle-cache-{{ checksum "build.gradle" }}
      - setup_remote_docker:
          version: 20.10.6
      - run:
          name: Building Arya Bot
          command: |
            # Skip this for other nodes
            ./gradlew buildAryaBot
